### PR TITLE
Use rabbit/gtk

### PR DESCRIPTION
**Pull request by okkez**
This is the first step to upgrade Gtk+3.

### CODE REVIEW

**Comment by kou** [comment]
We need #56 change before this change. Please rebase this.

**Comment by okkez** [comment]
Rebased. But I think this PR fails tests.

**Comment by kou** [comment]
Oh...

Please remove 122c0d046cc761dea5603de5ec54b8589b1faa76 from this pull request.

**Comment by okkez** [comment]
Removed 122c0d0.

**Pull request merged**
