### PR TITLE
Improve development doc.

### PR DESCRIPTION
**Pull request by masayuki14**
Added document about how to make development environment (ja).
Is page of document  better than faq page ?
I will add changes to english page after decide.

### CODE REVIEW

**Comment by kou** [comment]
Thanks!

> Is page of document better than faq page ?

"development' page is better.

> I will add changes to english page after decide.

Go ahead!

**Comment by masayuki14** [comment]
> Go ahead!

I did it!

**Comment by kou** [comment]
Good!
I've deployed the change: https://rabbit-shocker.org/ja/development.html

**Comment by kou** [comment]
The https://github.com/rabbit-shocker/rabbit/pull/106/commits/fe9f2f7c49bf4d6eaf6d64bd123f462095385e61 commit is good! Because I understand that you checked other documents and keep consistency. :-)

**Comment by masayuki14** [comment]
Thanks, I'm glad to be said that.😄

**Pull request merged**
